### ISSUE TITLE
Be able to specify another separactor

### ISSUE THREAD

**Issue by jogelin** [killerchip/ngx-translate-extract-csv#3]
By default, the separator of a CSV is a comma but it is possible to use other separator like tab, semicolon, space, etc...

What do you think about having the possibility to overwrite the separator like this:

`ngx-translate-extract-csv -l fr,nl -s ";"`

**Comment by killerchip** [comment]
Thanks jogelin for the suggestion.
I'll do at first chance...

**Comment by killerchip** [comment]
solved in v1.1.1
